name: Docker CI for microservice-voting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        env:
          ECR_REGISTRY: 194722430197.dkr.ecr.us-west-2.amazonaws.com
          ECR_REPOSITORY: training/craftista-voting
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Run Docker container for testing
        env:
          ECR_REGISTRY: 194722430197.dkr.ecr.us-west-2.amazonaws.com
          ECR_REPOSITORY: training/craftista-voting
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker run -d -p 8080:8080 --name microservice-voting-container $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Wait for the container to be ready
        run: sleep 30

      - name: Test Docker container
        run: |
          curl -f http://localhost:8080 || exit 1

      - name: Push Docker image to Amazon ECR
        if: success()
        env:
          ECR_REGISTRY: 194722430197.dkr.ecr.us-west-2.amazonaws.com
          ECR_REPOSITORY: training/craftista-voting
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Clean up
        run: docker rm -f microservice-voting-container
